import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { SWRProvider } from "./providers/SWRProvider";
import ToasterProvider from "./providers/ToasterProvider";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SWRProvider>
          <ToasterProvider />
          {children}
        </SWRProvider>
      </body>
    </html>
  );
}
